var gameOfThrones = ['Tyrion Lannister',
'Cersei Lannister',
'Daenerys Targaryen',
'Jon Snow',
'Arya Stark',
'Sansa Stark',
'Jorah Mormont',
'Jaime Lannister',
'Samwell Tarly',
'Petyr Baelish',
'Theon Greyjoy',
'Varys',
'Tywin Lannister',
'Sandor Clegane',
'Joffrey Baratheon',
'Catelyn Stark',
'Bran Stark',
'Brienne of Tarth',
'Bronn',
'Robb Stark',
'Shae',
'Stannis Baratheon',
'Margaery Tyrell',
'Missandei',
'Davos Seaworth',
'Gendry',
'Ygritte',
'Tommen Baratheon',
'Melisandre',
'Roose Bolton',
'Gilly',
'Tormund Giantsbane',
'Jeor Mormont',
'Daario Naharis',
'Talisa Stark',
'Eddard Stark',
'Khal Drogo',
'Ramsay Bolton',
'Jaqen H\'ghar',
'Olenna Tyrell',
'Robert Baratheon',
'Ellaria Sand',
'Viserys Targaryen'];

module.exports = [gameOfThrones];
